import React,{useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
type Turn={who:"customer"|"agent";text:string};
type Intake={intent:string;issue:string;area:string;preferredTime:string;name:string;urgency:string;nextAction:string};
const emptyIntake: Intake={intent:"未判定",issue:"",area:"",preferredTime:"",name:"",urgency:"通常",nextAction:""};
function deriveIntake(turns:Turn[]):Intake{const all=turns.filter(x=>x.who==="customer").map(x=>x.text).join(" ");const intent=/見積|料金/.test(all)?"見積":/予約|来て|訪問/.test(all)?"予約":/折り返|電話して/.test(all)?"折り返し":/故障|冷えない|水漏れ|異音/.test(all)?"修理相談":"未判定";return{...emptyIntake,intent,issue:all,urgency:/煙|火|焦げ|漏電/.test(all)?"緊急":"通常",nextAction:intent==="見積"?"見積担当へ引継ぎ":intent==="予約"?"訪問可否を担当者確認":intent==="修理相談"?"技術担当から折り返し":all?"内容確認":" "}}
function reply(t:string,history:Turn[]){const all=(history.filter(x=>x.who==="customer").map(x=>x.text).join(" ")+" "+t).trim();if(/煙|火|焦げ|漏電/.test(t))return"安全を優先してください。可能であれば機器の使用を中止し、安全な場所へ移動してください。担当者へ緊急として引き継ぎます。";if(/水漏れ/.test(t))return"水漏れですね。設置されている場所と、現在も運転中かを教えてください。";if(/冷えない|故障|異音/.test(t))return"承知しました。症状を確認します。設置されている地域と、いつ頃からその症状が出ているか教えてください。";if(/見積|料金/.test(t))return"お見積ですね。設置・交換・修理のどれをご希望かと、設置場所の地域を教えてください。";if(/予約|来て|訪問/.test(t))return"訪問のご希望ですね。地域と、ご都合のよい日時を教えてください。";if(/長野|上田|市|町|村/.test(t)&&!/名前|申します/.test(all))return"ありがとうございます。担当者からご連絡できるよう、お名前をお願いします。";if(/です|申します/.test(t))return"ありがとうございます。内容を担当者へ引き継ぎます。折り返し可能な時間帯にご希望があれば教えてください。";return"承知しました。担当者へ正確に引き継ぐため、もう少し詳しくお聞かせください。";}
function App(){const[turns,setTurns]=useState<Turn[]>([{who:"agent",text:"お電話ありがとうございます。和讃堂エアコン受付です。本日はどのようなご用件でしょうか？"}]);const[text,setText]=useState("");const[active,setActive]=useState(false);
function send(){if(!text.trim())return;const q=text.trim();setTurns(v=>[...v,{who:"customer",text:q},{who:"agent",text:reply(q,v)}]);setText("")}
function speak(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){alert("このブラウザでは音声認識を利用できません。Chromeでお試しください。");return}const r=new SR();r.lang="ja-JP";r.interimResults=false;r.onstart=()=>setActive(true);r.onend=()=>setActive(false);r.onresult=(e:any)=>setText(e.results[0][0].transcript);r.start()}
const customer=turns.filter(x=>x.who==="customer").map(x=>x.text).join(" / ");const intake=deriveIntake(turns);
return <main><header><b>WaSanDo CALL</b><span>AI電話受付</span></header><section className="hero"><div><p className="eyebrow">電話対応を止めない</p><h1>出られない電話も、<br/>その場で受付。</h1><p>接客中や営業時間外の電話にAIが応答。用件を聞き取り、見積・予約・折り返しに必要な情報を担当者へ引き継ぎます。</p><div className="heroPoints"><span>24時間受付</span><span>会話を自動記録</span><span>見積・予約へ引継ぎ</span></div></div><div className="status"><i className={active?"live":""}/>{active?"聞き取り中":"受付可能"}</div></section><section className="grid"><div className="panel"><div className="panelHead"><div><small>LIVE CALL</small><h2>電話受付</h2></div><span>デモ</span></div><div className="transcript">{turns.map((x,i)=><div key={i} className={x.who}><small>{x.who==="agent"?"受付":"お客様"}</small>{x.text}</div>)}</div><div className="composer"><button onClick={speak}>🎙 話す</button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="音声認識結果 / テスト入力"/><button onClick={send}>送信</button></div></div><aside className="panel"><div className="panelHead"><div><small>CALL SUMMARY</small><h2>受付内容</h2></div></div><dl><dt>業種</dt><dd>空調設備</dd><dt>用件</dt><dd>{intake.intent}</dd><dt>受付内容</dt><dd>{customer||"—"}</dd><dt>緊急度</dt><dd>{customer?intake.urgency:"—"}</dd><dt>次の処理</dt><dd>{customer?intake.nextAction:"—"}</dd></dl><div className="recordTags"><span>会話記録</span><span>要件整理</span><span>担当者へ引継ぎ</span></div></aside></section></main>}createRoot(document.getElementById("root")!).render(<App/>);